name: npm cleanup

on:
  workflow_dispatch:

jobs:
  unpublish-wrong-version:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Unpublish accidental version
        run: npm unpublish n8n-nodes-postora@0.0.1 --force
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
